### ISSUE TITLE
Please share Screenshots 

### ISSUE THREAD

**Issue by GeorgeS2019** [aGuyWhoMadeGames/planet#2]
I am familiar with the Youtube of Unity, it would be great to immediately see how far you have implemented in Godot4, where are the similarities and differences wrt to Unity implementation.

**Comment by aGuyWhoMadeGames** [comment]
Like I said, this is not a Godot port of that game. It is a completely separate game. The main similarity is that they both have a planet. You are right though, I do need to make a readme. For now, you can just open the project in Godot.

**Comment by aGuyWhoMadeGames** [comment]
I added a readme with some screenshots.
